workflows:
  react_vite_build:
    name: React Vite Build
    instance_type: linux_x2
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build the project
        script: npm run build
    artifacts:
      - dist/** # Saves built files
    publishing:
      email:
        recipients:
          - your-email@example.com
